sample_response = {
    "id": 6136777,
    "forecast_list": [
        {
            "date_string": "2024-12-02 01:00",
            "temperature": -2.55,
            "feels_like": -2.55,
            "temp_min": -2.55,
            "temp_max": -1.01,
            "pressure": 1031,
            "humidity": 89,
            "conditions": "clear sky",
            "cloud_cover_percent": 0,
            "chance_of_precipitation": 0,
            "wind_speed": 1.05,
            "wind_direction": 179,
        },
        {
            "date_string": "2024-12-02 04:00",
            "temperature": -2.15,
            "feels_like": -2.15,
            "temp_min": -2.15,
            "temp_max": -1.35,
            "pressure": 1031,
            "humidity": 88,
            "conditions": "few clouds",
            "cloud_cover_percent": 18,
            "chance_of_precipitation": 0,
            "wind_speed": 1.27,
            "wind_direction": 184,
        },
        {
            "date_string": "2024-12-02 07:00",
            "temperature": -1.9,
            "feels_like": -1.9,
            "temp_min": -1.9,
            "temp_max": -1.58,
            "pressure": 1031,
            "humidity": 87,
            "conditions": "scattered clouds",
            "cloud_cover_percent": 36,
            "chance_of_precipitation": 0,
            "wind_speed": 1.2,
            "wind_direction": 179,
        },
        {
            "date_string": "2024-12-02 10:00",
            "temperature": 1.75,
            "feels_like": -0.19,
            "temp_min": 1.75,
            "temp_max": 1.75,
            "pressure": 1030,
            "humidity": 71,
            "conditions": "scattered clouds",
            "cloud_cover_percent": 35,
            "chance_of_precipitation": 0,
            "wind_speed": 1.81,
            "wind_direction": 200,
        },
        {
            "date_string": "2024-12-02 13:00",
            "temperature": 4.29,
            "feels_like": 2.48,
            "temp_min": 4.29,
            "temp_max": 4.29,
            "pressure": 1028,
            "humidity": 64,
            "conditions": "clear sky",
            "cloud_cover_percent": 6,
            "chance_of_precipitation": 0,
            "wind_speed": 2.06,
            "wind_direction": 205,
        },
        {
            "date_string": "2024-12-02 16:00",
            "temperature": 1.08,
            "feels_like": -0.41,
            "temp_min": 1.08,
            "temp_max": 1.08,
            "pressure": 1028,
            "humidity": 82,
            "conditions": "clear sky",
            "cloud_cover_percent": 8,
            "chance_of_precipitation": 0,
            "wind_speed": 1.43,
            "wind_direction": 182,
        },
        {
            "date_string": "2024-12-02 19:00",
            "temperature": -0.02,
            "feels_like": -1.51,
            "temp_min": -0.02,
            "temp_max": -0.02,
            "pressure": 1029,
            "humidity": 83,
            "conditions": "clear sky",
            "cloud_cover_percent": 6,
            "chance_of_precipitation": 0,
            "wind_speed": 1.34,
            "wind_direction": 174,
        },
        {
            "date_string": "2024-12-02 22:00",
            "temperature": -0.4,
            "feels_like": -2.62,
            "temp_min": -0.4,
            "temp_max": -0.4,
            "pressure": 1030,
            "humidity": 78,
            "conditions": "few clouds",
            "cloud_cover_percent": 11,
            "chance_of_precipitation": 0,
            "wind_speed": 1.77,
            "wind_direction": 174,
        },
        {
            "date_string": "2024-12-03 01:00",
            "temperature": -0.4,
            "feels_like": -2.82,
            "temp_min": -0.4,
            "temp_max": -0.4,
            "pressure": 1029,
            "humidity": 75,
            "conditions": "broken clouds",
            "cloud_cover_percent": 84,
            "chance_of_precipitation": 0,
            "wind_speed": 1.92,
            "wind_direction": 176,
        },
        {
            "date_string": "2024-12-03 04:00",
            "temperature": -0.98,
            "feels_like": -0.98,
            "temp_min": -0.98,
            "temp_max": -0.98,
            "pressure": 1030,
            "humidity": 75,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 86,
            "chance_of_precipitation": 0,
            "wind_speed": 0.9,
            "wind_direction": 183,
        },
        {
            "date_string": "2024-12-03 07:00",
            "temperature": -1.11,
            "feels_like": -1.11,
            "temp_min": -1.11,
            "temp_max": -1.11,
            "pressure": 1031,
            "humidity": 74,
            "conditions": "broken clouds",
            "cloud_cover_percent": 61,
            "chance_of_precipitation": 0,
            "wind_speed": 1.25,
            "wind_direction": 158,
        },
        {
            "date_string": "2024-12-03 10:00",
            "temperature": 2.21,
            "feels_like": 2.21,
            "temp_min": 2.21,
            "temp_max": 2.21,
            "pressure": 1030,
            "humidity": 60,
            "conditions": "scattered clouds",
            "cloud_cover_percent": 44,
            "chance_of_precipitation": 0,
            "wind_speed": 0.78,
            "wind_direction": 220,
        },
        {
            "date_string": "2024-12-03 13:00",
            "temperature": 4.58,
            "feels_like": 4.58,
            "temp_min": 4.58,
            "temp_max": 4.58,
            "pressure": 1029,
            "humidity": 55,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 98,
            "chance_of_precipitation": 0,
            "wind_speed": 0.64,
            "wind_direction": 240,
        },
        {
            "date_string": "2024-12-03 16:00",
            "temperature": 1.99,
            "feels_like": 1.99,
            "temp_min": 1.99,
            "temp_max": 1.99,
            "pressure": 1029,
            "humidity": 74,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 92,
            "chance_of_precipitation": 0,
            "wind_speed": 0.44,
            "wind_direction": 167,
        },
        {
            "date_string": "2024-12-03 19:00",
            "temperature": 0.98,
            "feels_like": 0.98,
            "temp_min": 0.98,
            "temp_max": 0.98,
            "pressure": 1030,
            "humidity": 78,
            "conditions": "scattered clouds",
            "cloud_cover_percent": 39,
            "chance_of_precipitation": 0,
            "wind_speed": 0.98,
            "wind_direction": 165,
        },
        {
            "date_string": "2024-12-03 22:00",
            "temperature": 0.75,
            "feels_like": 0.75,
            "temp_min": 0.75,
            "temp_max": 0.75,
            "pressure": 1030,
            "humidity": 75,
            "conditions": "broken clouds",
            "cloud_cover_percent": 52,
            "chance_of_precipitation": 0,
            "wind_speed": 1.24,
            "wind_direction": 174,
        },
        {
            "date_string": "2024-12-04 01:00",
            "temperature": 0.8,
            "feels_like": 0.8,
            "temp_min": 0.8,
            "temp_max": 0.8,
            "pressure": 1030,
            "humidity": 74,
            "conditions": "broken clouds",
            "cloud_cover_percent": 70,
            "chance_of_precipitation": 0,
            "wind_speed": 1.25,
            "wind_direction": 176,
        },
        {
            "date_string": "2024-12-04 04:00",
            "temperature": 0.9,
            "feels_like": 0.9,
            "temp_min": 0.9,
            "temp_max": 0.9,
            "pressure": 1029,
            "humidity": 72,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 85,
            "chance_of_precipitation": 0,
            "wind_speed": 1.25,
            "wind_direction": 178,
        },
        {
            "date_string": "2024-12-04 07:00",
            "temperature": 0.38,
            "feels_like": -1.26,
            "temp_min": 0.38,
            "temp_max": 0.38,
            "pressure": 1029,
            "humidity": 72,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 99,
            "chance_of_precipitation": 0,
            "wind_speed": 1.46,
            "wind_direction": 173,
        },
        {
            "date_string": "2024-12-04 10:00",
            "temperature": 3.41,
            "feels_like": 1.86,
            "temp_min": 3.41,
            "temp_max": 3.41,
            "pressure": 1028,
            "humidity": 59,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 93,
            "chance_of_precipitation": 0,
            "wind_speed": 1.71,
            "wind_direction": 195,
        },
        {
            "date_string": "2024-12-04 13:00",
            "temperature": 4.82,
            "feels_like": 3.48,
            "temp_min": 4.82,
            "temp_max": 4.82,
            "pressure": 1026,
            "humidity": 63,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 92,
            "chance_of_precipitation": 0,
            "wind_speed": 1.71,
            "wind_direction": 206,
        },
        {
            "date_string": "2024-12-04 16:00",
            "temperature": 2.56,
            "feels_like": 1.18,
            "temp_min": 2.56,
            "temp_max": 2.56,
            "pressure": 1026,
            "humidity": 80,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 96,
            "chance_of_precipitation": 0,
            "wind_speed": 1.49,
            "wind_direction": 172,
        },
        {
            "date_string": "2024-12-04 19:00",
            "temperature": 2,
            "feels_like": 2,
            "temp_min": 2,
            "temp_max": 2,
            "pressure": 1026,
            "humidity": 82,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 100,
            "chance_of_precipitation": 0,
            "wind_speed": 1.33,
            "wind_direction": 170,
        },
        {
            "date_string": "2024-12-04 22:00",
            "temperature": 1.04,
            "feels_like": 1.04,
            "temp_min": 1.04,
            "temp_max": 1.04,
            "pressure": 1026,
            "humidity": 82,
            "conditions": "broken clouds",
            "cloud_cover_percent": 73,
            "chance_of_precipitation": 0,
            "wind_speed": 1.24,
            "wind_direction": 180,
        },
        {
            "date_string": "2024-12-05 01:00",
            "temperature": 0.9,
            "feels_like": -0.79,
            "temp_min": 0.9,
            "temp_max": 0.9,
            "pressure": 1026,
            "humidity": 80,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 90,
            "chance_of_precipitation": 0,
            "wind_speed": 1.54,
            "wind_direction": 180,
        },
        {
            "date_string": "2024-12-05 04:00",
            "temperature": 1.24,
            "feels_like": -0.55,
            "temp_min": 1.24,
            "temp_max": 1.24,
            "pressure": 1025,
            "humidity": 79,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 95,
            "chance_of_precipitation": 0,
            "wind_speed": 1.64,
            "wind_direction": 187,
        },
        {
            "date_string": "2024-12-05 07:00",
            "temperature": 2.01,
            "feels_like": -0.1,
            "temp_min": 2.01,
            "temp_max": 2.01,
            "pressure": 1025,
            "humidity": 78,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 100,
            "chance_of_precipitation": 0,
            "wind_speed": 1.99,
            "wind_direction": 176,
        },
        {
            "date_string": "2024-12-05 10:00",
            "temperature": 2.86,
            "feels_like": 0.92,
            "temp_min": 2.86,
            "temp_max": 2.86,
            "pressure": 1025,
            "humidity": 80,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 100,
            "chance_of_precipitation": 0,
            "wind_speed": 1.96,
            "wind_direction": 182,
        },
        {
            "date_string": "2024-12-05 13:00",
            "temperature": 4.53,
            "feels_like": 2.49,
            "temp_min": 4.53,
            "temp_max": 4.53,
            "pressure": 1022,
            "humidity": 72,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 100,
            "chance_of_precipitation": 0.01,
            "wind_speed": 2.34,
            "wind_direction": 197,
        },
        {
            "date_string": "2024-12-05 16:00",
            "temperature": 1.85,
            "feels_like": -0.35,
            "temp_min": 1.85,
            "temp_max": 1.85,
            "pressure": 1023,
            "humidity": 89,
            "conditions": "broken clouds",
            "cloud_cover_percent": 74,
            "chance_of_precipitation": 0,
            "wind_speed": 2.04,
            "wind_direction": 187,
        },
        {
            "date_string": "2024-12-05 19:00",
            "temperature": 1.57,
            "feels_like": -0.51,
            "temp_min": 1.57,
            "temp_max": 1.57,
            "pressure": 1024,
            "humidity": 87,
            "conditions": "broken clouds",
            "cloud_cover_percent": 68,
            "chance_of_precipitation": 0,
            "wind_speed": 1.9,
            "wind_direction": 175,
        },
        {
            "date_string": "2024-12-05 22:00",
            "temperature": 3.17,
            "feels_like": 1.46,
            "temp_min": 3.17,
            "temp_max": 3.17,
            "pressure": 1024,
            "humidity": 84,
            "conditions": "broken clouds",
            "cloud_cover_percent": 82,
            "chance_of_precipitation": 0,
            "wind_speed": 1.81,
            "wind_direction": 183,
        },
        {
            "date_string": "2024-12-06 01:00",
            "temperature": 2.72,
            "feels_like": 0.72,
            "temp_min": 2.72,
            "temp_max": 2.72,
            "pressure": 1025,
            "humidity": 86,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 99,
            "chance_of_precipitation": 0,
            "wind_speed": 1.99,
            "wind_direction": 174,
        },
        {
            "date_string": "2024-12-06 04:00",
            "temperature": 1.74,
            "feels_like": -0.57,
            "temp_min": 1.74,
            "temp_max": 1.74,
            "pressure": 1025,
            "humidity": 90,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 91,
            "chance_of_precipitation": 0,
            "wind_speed": 2.12,
            "wind_direction": 179,
        },
        {
            "date_string": "2024-12-06 07:00",
            "temperature": 1.31,
            "feels_like": -0.67,
            "temp_min": 1.31,
            "temp_max": 1.31,
            "pressure": 1025,
            "humidity": 94,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 98,
            "chance_of_precipitation": 0,
            "wind_speed": 1.79,
            "wind_direction": 185,
        },
        {
            "date_string": "2024-12-06 10:00",
            "temperature": 3.36,
            "feels_like": 1.9,
            "temp_min": 3.36,
            "temp_max": 3.36,
            "pressure": 1024,
            "humidity": 91,
            "conditions": "light snow",
            "cloud_cover_percent": 99,
            "chance_of_precipitation": 0.28,
            "wind_speed": 1.63,
            "wind_direction": 187,
        },
        {
            "date_string": "2024-12-06 13:00",
            "temperature": 3.58,
            "feels_like": 2.46,
            "temp_min": 3.58,
            "temp_max": 3.58,
            "pressure": 1022,
            "humidity": 96,
            "conditions": "snow",
            "cloud_cover_percent": 100,
            "chance_of_precipitation": 1,
            "wind_speed": 1.41,
            "wind_direction": 191,
        },
        {
            "date_string": "2024-12-06 16:00",
            "temperature": 3.7,
            "feels_like": 2.17,
            "temp_min": 3.7,
            "temp_max": 3.7,
            "pressure": 1020,
            "humidity": 93,
            "conditions": "overcast clouds",
            "cloud_cover_percent": 100,
            "chance_of_precipitation": 0.8,
            "wind_speed": 1.73,
            "wind_direction": 195,
        },
        {
            "date_string": "2024-12-06 19:00",
            "temperature": 3.58,
            "feels_like": 1.68,
            "temp_min": 3.58,
            "temp_max": 3.58,
            "pressure": 1018,
            "humidity": 95,
            "conditions": "light snow",
            "cloud_cover_percent": 100,
            "chance_of_precipitation": 0.36,
            "wind_speed": 2.03,
            "wind_direction": 174,
        },
        {
            "date_string": "2024-12-06 22:00",
            "temperature": 3.77,
            "feels_like": 1.86,
            "temp_min": 3.77,
            "temp_max": 3.77,
            "pressure": 1015,
            "humidity": 94,
            "conditions": "light rain",
            "cloud_cover_percent": 100,
            "chance_of_precipitation": 0.25,
            "wind_speed": 2.07,
            "wind_direction": 189,
        },
    ],
}
