sample_response = {
    "cod": "200",
    "message": 0,
    "cnt": 40,
    "list": [
        {
            "dt": 1732611600,
            "main": {
                "temp": 0.03,
                "feels_like": 0.03,
                "temp_min": -0.62,
                "temp_max": 0.03,
                "pressure": 1019,
                "sea_level": 1019,
                "grnd_level": 903,
                "humidity": 93,
                "temp_kf": 0.65,
            },
            "weather": [
                {"id": 600, "main": "Snow", "description": "light snow", "icon": "13n"}
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 0.35, "deg": 44, "gust": 0.76},
            "visibility": 2095,
            "pop": 0.2,
            "snow": {"3h": 0.18},
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-26 09:00:00",
        },
        {
            "dt": 1732622400,
            "main": {
                "temp": -0.97,
                "feels_like": -0.97,
                "temp_min": -1.63,
                "temp_max": -0.97,
                "pressure": 1020,
                "sea_level": 1020,
                "grnd_level": 903,
                "humidity": 93,
                "temp_kf": 0.66,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 95},
            "wind": {"speed": 0.48, "deg": 42, "gust": 0.97},
            "visibility": 1211,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-26 12:00:00",
        },
        {
            "dt": 1732633200,
            "main": {
                "temp": -1.61,
                "feels_like": -1.61,
                "temp_min": -1.61,
                "temp_max": -1.61,
                "pressure": 1020,
                "sea_level": 1020,
                "grnd_level": 904,
                "humidity": 94,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 96},
            "wind": {"speed": 0.55, "deg": 151, "gust": 0.79},
            "visibility": 2504,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-26 15:00:00",
        },
        {
            "dt": 1732644000,
            "main": {
                "temp": 1.3,
                "feels_like": 1.3,
                "temp_min": 1.3,
                "temp_max": 1.3,
                "pressure": 1020,
                "sea_level": 1020,
                "grnd_level": 905,
                "humidity": 82,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 97},
            "wind": {"speed": 0.58, "deg": 221, "gust": 0.95},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-26 18:00:00",
        },
        {
            "dt": 1732654800,
            "main": {
                "temp": 3.28,
                "feels_like": 3.28,
                "temp_min": 3.28,
                "temp_max": 3.28,
                "pressure": 1019,
                "sea_level": 1019,
                "grnd_level": 905,
                "humidity": 74,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 0.3, "deg": 284, "gust": 0.58},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-26 21:00:00",
        },
        {
            "dt": 1732665600,
            "main": {
                "temp": 0.05,
                "feels_like": 0.05,
                "temp_min": 0.05,
                "temp_max": 0.05,
                "pressure": 1021,
                "sea_level": 1021,
                "grnd_level": 905,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 97},
            "wind": {"speed": 0.79, "deg": 86, "gust": 0.66},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-27 00:00:00",
        },
        {
            "dt": 1732676400,
            "main": {
                "temp": -1.43,
                "feels_like": -1.43,
                "temp_min": -1.43,
                "temp_max": -1.43,
                "pressure": 1023,
                "sea_level": 1023,
                "grnd_level": 907,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 87},
            "wind": {"speed": 0.51, "deg": 102, "gust": 0.81},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-27 03:00:00",
        },
        {
            "dt": 1732687200,
            "main": {
                "temp": -1.59,
                "feels_like": -1.59,
                "temp_min": -1.59,
                "temp_max": -1.59,
                "pressure": 1024,
                "sea_level": 1024,
                "grnd_level": 907,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 83},
            "wind": {"speed": 0.64, "deg": 161, "gust": 0.91},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-27 06:00:00",
        },
        {
            "dt": 1732698000,
            "main": {
                "temp": -1.63,
                "feels_like": -1.63,
                "temp_min": -1.63,
                "temp_max": -1.63,
                "pressure": 1024,
                "sea_level": 1024,
                "grnd_level": 908,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 1.26, "deg": 178, "gust": 1.28},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-27 09:00:00",
        },
        {
            "dt": 1732708800,
            "main": {
                "temp": -2.34,
                "feels_like": -2.34,
                "temp_min": -2.34,
                "temp_max": -2.34,
                "pressure": 1025,
                "sea_level": 1025,
                "grnd_level": 908,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 1.24, "deg": 167, "gust": 1.2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-27 12:00:00",
        },
        {
            "dt": 1732719600,
            "main": {
                "temp": -3.47,
                "feels_like": -5.95,
                "temp_min": -3.47,
                "temp_max": -3.47,
                "pressure": 1026,
                "sea_level": 1026,
                "grnd_level": 909,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 85},
            "wind": {"speed": 1.64, "deg": 172, "gust": 2.04},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-27 15:00:00",
        },
        {
            "dt": 1732730400,
            "main": {
                "temp": 0.91,
                "feels_like": -0.61,
                "temp_min": 0.91,
                "temp_max": 0.91,
                "pressure": 1026,
                "sea_level": 1026,
                "grnd_level": 910,
                "humidity": 73,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 50},
            "wind": {"speed": 1.43, "deg": 198, "gust": 1.79},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-27 18:00:00",
        },
        {
            "dt": 1732741200,
            "main": {
                "temp": 2.98,
                "feels_like": 2.98,
                "temp_min": 2.98,
                "temp_max": 2.98,
                "pressure": 1025,
                "sea_level": 1025,
                "grnd_level": 910,
                "humidity": 65,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 94},
            "wind": {"speed": 0.62, "deg": 211, "gust": 1.11},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-27 21:00:00",
        },
        {
            "dt": 1732752000,
            "main": {
                "temp": -0.81,
                "feels_like": -0.81,
                "temp_min": -0.81,
                "temp_max": -0.81,
                "pressure": 1026,
                "sea_level": 1026,
                "grnd_level": 909,
                "humidity": 86,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 96},
            "wind": {"speed": 0.67, "deg": 120, "gust": 0.74},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-28 00:00:00",
        },
        {
            "dt": 1732762800,
            "main": {
                "temp": -2.83,
                "feels_like": -2.83,
                "temp_min": -2.83,
                "temp_max": -2.83,
                "pressure": 1028,
                "sea_level": 1028,
                "grnd_level": 911,
                "humidity": 89,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 80},
            "wind": {"speed": 0.87, "deg": 128, "gust": 1.07},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-28 03:00:00",
        },
        {
            "dt": 1732773600,
            "main": {
                "temp": -3.53,
                "feels_like": -3.53,
                "temp_min": -3.53,
                "temp_max": -3.53,
                "pressure": 1029,
                "sea_level": 1029,
                "grnd_level": 911,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 65},
            "wind": {"speed": 0.86, "deg": 143, "gust": 1},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-28 06:00:00",
        },
        {
            "dt": 1732784400,
            "main": {
                "temp": -3.59,
                "feels_like": -3.59,
                "temp_min": -3.59,
                "temp_max": -3.59,
                "pressure": 1029,
                "sea_level": 1029,
                "grnd_level": 911,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 1.11, "deg": 152, "gust": 1.14},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-28 09:00:00",
        },
        {
            "dt": 1732795200,
            "main": {
                "temp": -3.13,
                "feels_like": -3.13,
                "temp_min": -3.13,
                "temp_max": -3.13,
                "pressure": 1029,
                "sea_level": 1029,
                "grnd_level": 911,
                "humidity": 88,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 0.93, "deg": 154, "gust": 1.01},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-28 12:00:00",
        },
        {
            "dt": 1732806000,
            "main": {
                "temp": -3.09,
                "feels_like": -3.09,
                "temp_min": -3.09,
                "temp_max": -3.09,
                "pressure": 1028,
                "sea_level": 1028,
                "grnd_level": 911,
                "humidity": 88,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 0.38, "deg": 147, "gust": 0.82},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-28 15:00:00",
        },
        {
            "dt": 1732816800,
            "main": {
                "temp": -0.36,
                "feels_like": -0.36,
                "temp_min": -0.36,
                "temp_max": -0.36,
                "pressure": 1028,
                "sea_level": 1028,
                "grnd_level": 911,
                "humidity": 76,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 0.62, "deg": 227, "gust": 0.88},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-28 18:00:00",
        },
        {
            "dt": 1732827600,
            "main": {
                "temp": 1.31,
                "feels_like": 1.31,
                "temp_min": 1.31,
                "temp_max": 1.31,
                "pressure": 1026,
                "sea_level": 1026,
                "grnd_level": 910,
                "humidity": 69,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 0.66, "deg": 241, "gust": 0.91},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-28 21:00:00",
        },
        {
            "dt": 1732838400,
            "main": {
                "temp": -1.7,
                "feels_like": -1.7,
                "temp_min": -1.7,
                "temp_max": -1.7,
                "pressure": 1027,
                "sea_level": 1027,
                "grnd_level": 910,
                "humidity": 88,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 98},
            "wind": {"speed": 0.41, "deg": 112, "gust": 0.41},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-29 00:00:00",
        },
        {
            "dt": 1732849200,
            "main": {
                "temp": -3.12,
                "feels_like": -3.12,
                "temp_min": -3.12,
                "temp_max": -3.12,
                "pressure": 1027,
                "sea_level": 1027,
                "grnd_level": 910,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 88},
            "wind": {"speed": 1, "deg": 137, "gust": 1.08},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-29 03:00:00",
        },
        {
            "dt": 1732860000,
            "main": {
                "temp": -4.22,
                "feels_like": -6.42,
                "temp_min": -4.22,
                "temp_max": -4.22,
                "pressure": 1028,
                "sea_level": 1028,
                "grnd_level": 910,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 67},
            "wind": {"speed": 1.42, "deg": 156, "gust": 1.4},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-29 06:00:00",
        },
        {
            "dt": 1732870800,
            "main": {
                "temp": -4.89,
                "feels_like": -4.89,
                "temp_min": -4.89,
                "temp_max": -4.89,
                "pressure": 1028,
                "sea_level": 1028,
                "grnd_level": 909,
                "humidity": 92,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 40},
            "wind": {"speed": 1.11, "deg": 147, "gust": 1.27},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-29 09:00:00",
        },
        {
            "dt": 1732881600,
            "main": {
                "temp": -4.81,
                "feels_like": -7.61,
                "temp_min": -4.81,
                "temp_max": -4.81,
                "pressure": 1027,
                "sea_level": 1027,
                "grnd_level": 909,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 49},
            "wind": {"speed": 1.71, "deg": 168, "gust": 2.03},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-29 12:00:00",
        },
        {
            "dt": 1732892400,
            "main": {
                "temp": -3.67,
                "feels_like": -3.67,
                "temp_min": -3.67,
                "temp_max": -3.67,
                "pressure": 1027,
                "sea_level": 1027,
                "grnd_level": 910,
                "humidity": 85,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 1.33, "deg": 179, "gust": 1.4},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-29 15:00:00",
        },
        {
            "dt": 1732903200,
            "main": {
                "temp": -0.74,
                "feels_like": -2.36,
                "temp_min": -0.74,
                "temp_max": -0.74,
                "pressure": 1028,
                "sea_level": 1028,
                "grnd_level": 911,
                "humidity": 73,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 82},
            "wind": {"speed": 1.36, "deg": 191, "gust": 1.69},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-29 18:00:00",
        },
        {
            "dt": 1732914000,
            "main": {
                "temp": 1.57,
                "feels_like": 1.57,
                "temp_min": 1.57,
                "temp_max": 1.57,
                "pressure": 1027,
                "sea_level": 1027,
                "grnd_level": 911,
                "humidity": 66,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 86},
            "wind": {"speed": 0.18, "deg": 63, "gust": 0.45},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-29 21:00:00",
        },
        {
            "dt": 1732924800,
            "main": {
                "temp": -2.69,
                "feels_like": -2.69,
                "temp_min": -2.69,
                "temp_max": -2.69,
                "pressure": 1030,
                "sea_level": 1030,
                "grnd_level": 912,
                "humidity": 87,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 68},
            "wind": {"speed": 0.64, "deg": 97, "gust": 0.8},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-30 00:00:00",
        },
        {
            "dt": 1732935600,
            "main": {
                "temp": -3.79,
                "feels_like": -3.79,
                "temp_min": -3.79,
                "temp_max": -3.79,
                "pressure": 1032,
                "sea_level": 1032,
                "grnd_level": 914,
                "humidity": 89,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 82},
            "wind": {"speed": 0.89, "deg": 108, "gust": 1.12},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-30 03:00:00",
        },
        {
            "dt": 1732946400,
            "main": {
                "temp": -3.97,
                "feels_like": -3.97,
                "temp_min": -3.97,
                "temp_max": -3.97,
                "pressure": 1033,
                "sea_level": 1033,
                "grnd_level": 915,
                "humidity": 89,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 75},
            "wind": {"speed": 1.04, "deg": 148, "gust": 1.09},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-30 06:00:00",
        },
        {
            "dt": 1732957200,
            "main": {
                "temp": -4.33,
                "feels_like": -4.33,
                "temp_min": -4.33,
                "temp_max": -4.33,
                "pressure": 1034,
                "sea_level": 1034,
                "grnd_level": 915,
                "humidity": 91,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 0.78, "deg": 149, "gust": 1.07},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-30 09:00:00",
        },
        {
            "dt": 1732968000,
            "main": {
                "temp": -2.81,
                "feels_like": -2.81,
                "temp_min": -2.81,
                "temp_max": -2.81,
                "pressure": 1033,
                "sea_level": 1033,
                "grnd_level": 915,
                "humidity": 86,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 0.51, "deg": 182, "gust": 0.79},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-30 12:00:00",
        },
        {
            "dt": 1732978800,
            "main": {
                "temp": -4.04,
                "feels_like": -4.04,
                "temp_min": -4.04,
                "temp_max": -4.04,
                "pressure": 1034,
                "sea_level": 1034,
                "grnd_level": 915,
                "humidity": 91,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 1, "deg": 178, "gust": 1.18},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-11-30 15:00:00",
        },
        {
            "dt": 1732989600,
            "main": {
                "temp": -0.82,
                "feels_like": -0.82,
                "temp_min": -0.82,
                "temp_max": -0.82,
                "pressure": 1033,
                "sea_level": 1033,
                "grnd_level": 916,
                "humidity": 76,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 72},
            "wind": {"speed": 0.67, "deg": 206, "gust": 0.94},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-30 18:00:00",
        },
        {
            "dt": 1733000400,
            "main": {
                "temp": 1.51,
                "feels_like": 1.51,
                "temp_min": 1.51,
                "temp_max": 1.51,
                "pressure": 1032,
                "sea_level": 1032,
                "grnd_level": 915,
                "humidity": 68,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 85},
            "wind": {"speed": 0.4, "deg": 264, "gust": 0.67},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-11-30 21:00:00",
        },
        {
            "dt": 1733011200,
            "main": {
                "temp": -1.34,
                "feels_like": -1.34,
                "temp_min": -1.34,
                "temp_max": -1.34,
                "pressure": 1032,
                "sea_level": 1032,
                "grnd_level": 915,
                "humidity": 85,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 91},
            "wind": {"speed": 0.17, "deg": 155, "gust": 0.4},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-12-01 00:00:00",
        },
        {
            "dt": 1733022000,
            "main": {
                "temp": -2.4,
                "feels_like": -2.4,
                "temp_min": -2.4,
                "temp_max": -2.4,
                "pressure": 1033,
                "sea_level": 1033,
                "grnd_level": 915,
                "humidity": 89,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 0.55, "deg": 153, "gust": 1.02},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-12-01 03:00:00",
        },
        {
            "dt": 1733032800,
            "main": {
                "temp": -2.8,
                "feels_like": -2.8,
                "temp_min": -2.8,
                "temp_max": -2.8,
                "pressure": 1033,
                "sea_level": 1033,
                "grnd_level": 915,
                "humidity": 89,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 0.69, "deg": 152, "gust": 1.17},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-12-01 06:00:00",
        },
    ],
    "city": {
        "id": 6136777,
        "name": "Rutland",
        "coord": {"lat": 49.9397, "lon": -119.3964},
        "country": "CA",
        "population": 0,
        "timezone": -28800,
        "sunrise": 1732548408,
        "sunset": 1732579389,
    },
}
